---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
