apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netobserv-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: netobserv-operator
    repoURL: https://netobserv.io/static/helm/
    targetRevision: 1.9.1
    helm:
      releaseName: netobserv-operator
      valuesObject:
        standaloneConsole:
          enable: true
        install:
          loki: true
          prom: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netobserv
