kind: FlowCollector
apiVersion: flows.netobserv.io/v1beta2
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  agent:
    ebpf:
      logLevel: info
      metrics:
        server:
          port: 9400
      privileged: false
      sampling: 50
    type: eBPF
  consolePlugin:
    autoscaler:
      status: Disabled
    enable: true
    logLevel: info
    portNaming:
      enable: true
      portNames:
        '3100': loki
  loki:
    enable: false
  namespace: netobserv
  prometheus:
    querier:
      enable: true
      mode: Auto
      timeout: 30s
